apiVersion: v1
kind: Deployment
metadata:
  name: service-a-deployment
  labels:
    app: rep1
spec:
 replicas: 2
 selector:
  matchLabels:
    app: rep1
 template:
 metadata:
  labels:
    app: rep1
 spec:
  containers:
  - name: rep1
    image: rep1:testa
    ports:
    - containerPort: 80